--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/niuniu/resource/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(31)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Scene:addChild(bg)

--Create Image_17
local Image_17 = ccui.ImageView:create()
Image_17:ignoreContentAdaptWithSize(false)
Image_17:loadTexture("game/niuniu/resource/role.png",0)
Image_17:setLayoutComponentEnabled(true)
Image_17:setName("Image_17")
Image_17:setTag(1196)
Image_17:setCascadeColorEnabled(true)
Image_17:setCascadeOpacityEnabled(true)
Image_17:setAnchorPoint(0.5000, 0.0000)
Image_17:setPosition(360.0000, -2.7320)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_17)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.0021)
layout:setPercentWidth(1.7778)
layout:setPercentHeight(0.5625)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(-280.0000)
layout:setRightMargin(-280.0000)
layout:setTopMargin(562.7320)
layout:setBottomMargin(-2.7320)
Scene:addChild(Image_17)

--Create playBtn
local playBtn = ccui.Button:create()
playBtn:ignoreContentAdaptWithSize(false)
playBtn:loadTextureNormal("game/niuniu/resource/btn.png",0)
playBtn:setTitleFontName("game/niuniu/resource/font/font.TTF")
playBtn:setTitleFontSize(30)
playBtn:setTitleText("进入游戏")
playBtn:setScale9Enabled(true)
playBtn:setCapInsets({x = 15, y = 11, width = 195, height = 50})
playBtn:setLayoutComponentEnabled(true)
playBtn:setName("playBtn")
playBtn:setTag(155)
playBtn:setCascadeColorEnabled(true)
playBtn:setCascadeOpacityEnabled(true)
playBtn:setPosition(360.0000, 727.9360)
playBtn:setScaleX(1.5000)
playBtn:setScaleY(1.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(playBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5687)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.0563)
layout:setSize({width = 225.0000, height = 72.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(247.5000)
layout:setRightMargin(247.5000)
layout:setTopMargin(516.0640)
layout:setBottomMargin(691.9360)
Scene:addChild(playBtn)

--Create ruleBtn
local ruleBtn = ccui.Button:create()
ruleBtn:ignoreContentAdaptWithSize(false)
ruleBtn:loadTextureNormal("game/niuniu/resource/btn.png",0)
ruleBtn:setTitleFontName("game/niuniu/resource/font/font.TTF")
ruleBtn:setTitleFontSize(30)
ruleBtn:setTitleText("规 则")
ruleBtn:setScale9Enabled(true)
ruleBtn:setCapInsets({x = 15, y = 11, width = 195, height = 50})
ruleBtn:setLayoutComponentEnabled(true)
ruleBtn:setName("ruleBtn")
ruleBtn:setTag(453)
ruleBtn:setCascadeColorEnabled(true)
ruleBtn:setCascadeOpacityEnabled(true)
ruleBtn:setPosition(360.0000, 584.2460)
ruleBtn:setScaleX(1.5000)
ruleBtn:setScaleY(1.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4564)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.0563)
layout:setSize({width = 225.0000, height = 72.0000})
layout:setLeftMargin(247.5000)
layout:setRightMargin(247.5000)
layout:setTopMargin(659.7540)
layout:setBottomMargin(548.2460)
Scene:addChild(ruleBtn)

--Create scoreText
local scoreText = ccui.Text:create()
scoreText:ignoreContentAdaptWithSize(true)
scoreText:setTextAreaSize({width = 0, height = 0})
scoreText:setFontName("game/niuniu/resource/font/font.TTF")
scoreText:setFontSize(30)
scoreText:setString([[0]])
scoreText:setLayoutComponentEnabled(true)
scoreText:setName("scoreText")
scoreText:setTag(968)
scoreText:setCascadeColorEnabled(true)
scoreText:setCascadeOpacityEnabled(true)
scoreText:setAnchorPoint(0.0000, 0.5000)
scoreText:setPosition(436.4867, 1240.1720)
layout = ccui.LayoutComponent:bindLayoutComponent(scoreText)
layout:setPositionPercentX(0.6062)
layout:setPositionPercentY(0.9689)
layout:setPercentWidth(0.0306)
layout:setPercentHeight(0.0266)
layout:setSize({width = 22.0000, height = 34.0000})
layout:setLeftMargin(436.4867)
layout:setRightMargin(261.5133)
layout:setTopMargin(22.8279)
layout:setBottomMargin(1223.1720)
Scene:addChild(scoreText)

--Create bestText
local bestText = ccui.Text:create()
bestText:ignoreContentAdaptWithSize(true)
bestText:setTextAreaSize({width = 0, height = 0})
bestText:setFontName("game/niuniu/resource/font/font.TTF")
bestText:setFontSize(30)
bestText:setString([[历史最高分：]])
bestText:setLayoutComponentEnabled(true)
bestText:setName("bestText")
bestText:setTag(969)
bestText:setCascadeColorEnabled(true)
bestText:setCascadeOpacityEnabled(true)
bestText:setAnchorPoint(1.0000, 0.5000)
bestText:setPosition(418.8815, 1240.3950)
bestText:setRotationSkewX(-0.2955)
bestText:setRotationSkewY(-0.2938)
layout = ccui.LayoutComponent:bindLayoutComponent(bestText)
layout:setPositionPercentX(0.5818)
layout:setPositionPercentY(0.9691)
layout:setPercentWidth(0.2278)
layout:setPercentHeight(0.0266)
layout:setSize({width = 164.0000, height = 34.0000})
layout:setLeftMargin(254.8815)
layout:setRightMargin(301.1185)
layout:setTopMargin(22.6055)
layout:setBottomMargin(1223.3950)
Scene:addChild(bestText)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

