--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create root
local root = ccui.Layout:create()
root:ignoreContentAdaptWithSize(false)
root:setClippingEnabled(false)
root:setBackGroundColorOpacity(102)
root:setTouchEnabled(true);
root:setLayoutComponentEnabled(true)
root:setName("root")
root:setTag(9297)
root:setCascadeColorEnabled(true)
root:setCascadeOpacityEnabled(true)
root:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(root)
layout:setSize({width = 118.0000, height = 157.0000})
layout:setLeftMargin(-59.0000)
layout:setRightMargin(-59.0000)
layout:setTopMargin(-78.5000)
layout:setBottomMargin(-78.5000)
Node:addChild(root)

--Create pokerbg
local pokerbg = ccui.ImageView:create()
pokerbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/niuniu/resource/poker/poker.plist")
pokerbg:loadTexture("foreground.png",1)
pokerbg:setLayoutComponentEnabled(true)
pokerbg:setName("pokerbg")
pokerbg:setTag(164)
pokerbg:setCascadeColorEnabled(true)
pokerbg:setCascadeOpacityEnabled(true)
pokerbg:setPosition(59.0000, 78.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(pokerbg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 118.0000, height = 157.0000})
root:addChild(pokerbg)

--Create value
local value = ccui.ImageView:create()
value:ignoreContentAdaptWithSize(false)
value:loadTexture("Default/ImageFile.png",0)
value:setLayoutComponentEnabled(true)
value:setName("value")
value:setTag(271)
value:setCascadeColorEnabled(true)
value:setCascadeOpacityEnabled(true)
value:setVisible(false)
value:setPosition(28.4021, 127.7205)
value:setScaleX(1.3000)
value:setScaleY(1.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(value)
layout:setPositionPercentX(0.2407)
layout:setPositionPercentY(0.8135)
layout:setPercentWidth(0.3305)
layout:setPercentHeight(0.2166)
layout:setSize({width = 39.0000, height = 34.0000})
layout:setLeftMargin(8.9021)
layout:setRightMargin(70.0979)
layout:setTopMargin(12.2795)
layout:setBottomMargin(110.7205)
root:addChild(value)

--Create color
local color = ccui.ImageView:create()
color:ignoreContentAdaptWithSize(false)
color:loadTexture("Default/ImageFile.png",0)
color:setLayoutComponentEnabled(true)
color:setName("color")
color:setTag(272)
color:setCascadeColorEnabled(true)
color:setCascadeOpacityEnabled(true)
color:setVisible(false)
color:setPosition(28.4021, 84.4113)
color:setScaleX(1.3000)
color:setScaleY(1.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(color)
layout:setPositionPercentX(0.2407)
layout:setPositionPercentY(0.5377)
layout:setPercentWidth(0.2034)
layout:setPercentHeight(0.1592)
layout:setSize({width = 24.0000, height = 25.0000})
layout:setLeftMargin(16.4021)
layout:setRightMargin(77.5979)
layout:setTopMargin(60.0887)
layout:setBottomMargin(71.9113)
root:addChild(color)

--Create icon
local icon = ccui.ImageView:create()
icon:ignoreContentAdaptWithSize(false)
icon:loadTexture("Default/ImageFile.png",0)
icon:setLayoutComponentEnabled(true)
icon:setName("icon")
icon:setTag(273)
icon:setCascadeColorEnabled(true)
icon:setCascadeOpacityEnabled(true)
icon:setVisible(false)
icon:setPosition(80.3924, 43.2492)
icon:setScaleX(0.8000)
icon:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(icon)
layout:setPositionPercentX(0.6813)
layout:setPositionPercentY(0.2755)
layout:setPercentWidth(0.6525)
layout:setPercentHeight(0.5096)
layout:setSize({width = 77.0000, height = 80.0000})
layout:setLeftMargin(41.8924)
layout:setRightMargin(-0.8924)
layout:setTopMargin(73.7508)
layout:setBottomMargin(3.2492)
root:addChild(icon)

--Create zhuang
local zhuang = ccui.ImageView:create()
zhuang:ignoreContentAdaptWithSize(false)
zhuang:loadTexture("Default/ImageFile.png",0)
zhuang:setLayoutComponentEnabled(true)
zhuang:setName("zhuang")
zhuang:setTag(8)
zhuang:setCascadeColorEnabled(true)
zhuang:setCascadeOpacityEnabled(true)
zhuang:setVisible(false)
zhuang:setPosition(87.2330, 125.7206)
layout = ccui.LayoutComponent:bindLayoutComponent(zhuang)
layout:setPositionPercentX(0.7393)
layout:setPositionPercentY(0.8008)
layout:setPercentWidth(0.5339)
layout:setPercentHeight(0.3822)
layout:setSize({width = 63.0000, height = 60.0000})
layout:setLeftMargin(55.7330)
layout:setRightMargin(-0.7330)
layout:setTopMargin(1.2794)
layout:setBottomMargin(95.7206)
root:addChild(zhuang)

--Create clickbtn
local clickbtn = ccui.Button:create()
clickbtn:ignoreContentAdaptWithSize(false)
clickbtn:loadTextureDisabled("Default/Button_Disable.png",0)
clickbtn:setTitleFontSize(14)
clickbtn:setTitleColor({r = 65, g = 65, b = 70})
clickbtn:setScale9Enabled(true)
clickbtn:setCapInsets({x = -15, y = -11, width = 30, height = 22})
clickbtn:setTouchEnabled(false);
clickbtn:setLayoutComponentEnabled(true)
clickbtn:setName("clickbtn")
clickbtn:setTag(10716)
clickbtn:setCascadeColorEnabled(true)
clickbtn:setCascadeOpacityEnabled(true)
clickbtn:setVisible(false)
clickbtn:setPosition(76.9172, 61.0836)
layout = ccui.LayoutComponent:bindLayoutComponent(clickbtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.6518)
layout:setPositionPercentY(0.3891)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 118.0000, height = 157.0000})
layout:setLeftMargin(17.9172)
layout:setRightMargin(-17.9172)
layout:setTopMargin(17.4164)
layout:setBottomMargin(-17.4164)
root:addChild(clickbtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

