--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorType(1)
shade:setBackGroundColor({r = 26, g = 26, b = 26})
shade:setBackGroundColorOpacity(102)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(1329)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setPosition(-581.8494, -259.1857)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(-0.8081)
layout:setPositionPercentY(-0.2025)
layout:setPercentWidth(2.7778)
layout:setPercentHeight(1.5625)
layout:setSize({width = 2000.0000, height = 2000.0000})
layout:setLeftMargin(-581.8494)
layout:setRightMargin(-698.1506)
layout:setTopMargin(-460.8143)
layout:setBottomMargin(-259.1857)
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(27)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(362.0880, 641.5360)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentX(0.5029)
layout:setPositionPercentY(0.5012)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(2.0880)
layout:setRightMargin(-2.0880)
layout:setTopMargin(-1.5360)
layout:setBottomMargin(1.5360)
Layer:addChild(TopPanel)

--Create ruleBg
local ruleBg = cc.Sprite:create("game/niuniu/resource/rulewindow.png")
ruleBg:setName("ruleBg")
ruleBg:setTag(94)
ruleBg:setCascadeColorEnabled(true)
ruleBg:setCascadeOpacityEnabled(true)
ruleBg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.7778)
layout:setPercentHeight(0.5625)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(-280.0000)
layout:setRightMargin(-280.0000)
layout:setTopMargin(280.0000)
layout:setBottomMargin(280.0000)
ruleBg:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(ruleBg)

--Create win_text
local win_text = ccui.Text:create()
win_text:ignoreContentAdaptWithSize(true)
win_text:setTextAreaSize({width = 0, height = 0})
win_text:setFontName("game/niuniu/resource/font/font.TTF")
win_text:setFontSize(50)
win_text:setString([[Win]])
win_text:setLayoutComponentEnabled(true)
win_text:setName("win_text")
win_text:setTag(1328)
win_text:setCascadeColorEnabled(true)
win_text:setCascadeOpacityEnabled(true)
win_text:setPosition(123.3681, 766.0708)
layout = ccui.LayoutComponent:bindLayoutComponent(win_text)
layout:setPositionPercentX(0.1713)
layout:setPositionPercentY(0.5985)
layout:setPercentWidth(0.1181)
layout:setPercentHeight(0.0461)
layout:setSize({width = 85.0000, height = 59.0000})
layout:setLeftMargin(80.8681)
layout:setRightMargin(554.1318)
layout:setTopMargin(484.4292)
layout:setBottomMargin(736.5708)
TopPanel:addChild(win_text)

--Create List
local List = ccui.ListView:create()
List:setDirection(1)
List:setGravity(0)
List:ignoreContentAdaptWithSize(false)
List:setClippingEnabled(true)
List:setBackGroundColorOpacity(102)
List:setLayoutComponentEnabled(true)
List:setName("List")
List:setTag(1331)
List:setCascadeColorEnabled(true)
List:setCascadeOpacityEnabled(true)
List:setPosition(190.3784, 565.5886)
layout = ccui.LayoutComponent:bindLayoutComponent(List)
layout:setPositionPercentX(0.2644)
layout:setPositionPercentY(0.4419)
layout:setPercentWidth(0.5833)
layout:setPercentHeight(0.1563)
layout:setSize({width = 420.0000, height = 200.0000})
layout:setLeftMargin(190.3784)
layout:setRightMargin(109.6216)
layout:setTopMargin(514.4114)
layout:setBottomMargin(565.5886)
TopPanel:addChild(List)

--Create btn_return
local btn_return = ccui.Button:create()
btn_return:ignoreContentAdaptWithSize(false)
btn_return:loadTextureNormal("game/niuniu/resource/btn.png",0)
btn_return:setTitleFontName("game/niuniu/resource/font/font.TTF")
btn_return:setTitleFontSize(30)
btn_return:setTitleText("返回大厅")
btn_return:setTitleColor({r = 65, g = 65, b = 70})
btn_return:setLayoutComponentEnabled(true)
btn_return:setName("btn_return")
btn_return:setTag(1337)
btn_return:setCascadeColorEnabled(true)
btn_return:setCascadeOpacityEnabled(true)
btn_return:setPosition(360.4267, 504.7424)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_return)
layout:setPositionPercentX(0.5006)
layout:setPositionPercentY(0.3943)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.0562)
layout:setSize({width = 225.0000, height = 72.0000})
layout:setLeftMargin(247.9267)
layout:setRightMargin(247.0733)
layout:setTopMargin(739.2576)
layout:setBottomMargin(468.7424)
TopPanel:addChild(btn_return)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

