--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorType(1)
shade:setBackGroundColor({r = 26, g = 26, b = 26})
shade:setBackGroundColorOpacity(102)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(93)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setAnchorPoint(0.5000, 0.5000)
shade:setPosition(380.2883, 655.7416)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(0.5282)
layout:setPositionPercentY(0.5123)
layout:setPercentWidth(2.7778)
layout:setPercentHeight(1.5625)
layout:setSize({width = 2000.0000, height = 2000.0000})
layout:setLeftMargin(-619.7117)
layout:setRightMargin(-660.2883)
layout:setTopMargin(-375.7416)
layout:setBottomMargin(-344.2584)
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(27)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(362.0880, 641.5360)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentX(0.5029)
layout:setPositionPercentY(0.5012)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(2.0880)
layout:setRightMargin(-2.0880)
layout:setTopMargin(-1.5360)
layout:setBottomMargin(1.5360)
Layer:addChild(TopPanel)

--Create ruleBg
local ruleBg = cc.Sprite:create("game/niuniu/resource/rulewindow.png")
ruleBg:setName("ruleBg")
ruleBg:setTag(94)
ruleBg:setCascadeColorEnabled(true)
ruleBg:setCascadeOpacityEnabled(true)
ruleBg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.7778)
layout:setPercentHeight(0.5625)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(-280.0000)
layout:setRightMargin(-280.0000)
layout:setTopMargin(280.0000)
layout:setBottomMargin(280.0000)
ruleBg:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(ruleBg)

--Create contentText
local contentText = ccui.Text:create()
contentText:ignoreContentAdaptWithSize(true)
contentText:setTextAreaSize({width = 0, height = 0})
contentText:setFontName("game/niuniu/resource/font/font.TTF")
contentText:setFontSize(30)
contentText:setString([[正在游戏中，是否退出游戏？]])
contentText:setLayoutComponentEnabled(true)
contentText:setName("contentText")
contentText:setTag(38)
contentText:setCascadeColorEnabled(true)
contentText:setCascadeOpacityEnabled(true)
contentText:setPosition(640.0000, 436.6459)
layout = ccui.LayoutComponent:bindLayoutComponent(contentText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6065)
layout:setPercentWidth(0.2945)
layout:setPercentHeight(0.0486)
layout:setSize({width = 377.0000, height = 35.0000})
layout:setLeftMargin(451.5000)
layout:setRightMargin(451.5000)
layout:setTopMargin(265.8541)
layout:setBottomMargin(419.1459)
ruleBg:addChild(contentText)

--Create btn_yes
local btn_yes = ccui.Button:create()
btn_yes:ignoreContentAdaptWithSize(false)
btn_yes:loadTextureNormal("game/niuniu/resource/btn.png",0)
btn_yes:setTitleFontName("game/niuniu/resource/font/font.TTF")
btn_yes:setTitleFontSize(50)
btn_yes:setTitleText("是")
btn_yes:setTitleColor({r = 65, g = 65, b = 70})
btn_yes:setLayoutComponentEnabled(true)
btn_yes:setName("btn_yes")
btn_yes:setTag(1633)
btn_yes:setCascadeColorEnabled(true)
btn_yes:setCascadeOpacityEnabled(true)
btn_yes:setPosition(500.5672, 254.6320)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_yes)
layout:setPositionPercentX(0.3911)
layout:setPositionPercentY(0.3537)
layout:setPercentWidth(0.1758)
layout:setPercentHeight(0.1000)
layout:setSize({width = 225.0000, height = 72.0000})
layout:setLeftMargin(388.0672)
layout:setRightMargin(666.9328)
layout:setTopMargin(429.3680)
layout:setBottomMargin(218.6320)
ruleBg:addChild(btn_yes)

--Create btn_no
local btn_no = ccui.Button:create()
btn_no:ignoreContentAdaptWithSize(false)
btn_no:loadTextureNormal("game/niuniu/resource/btn.png",0)
btn_no:setTitleFontName("game/niuniu/resource/font/font.TTF")
btn_no:setTitleFontSize(50)
btn_no:setTitleText("否")
btn_no:setTitleColor({r = 65, g = 65, b = 70})
btn_no:setLayoutComponentEnabled(true)
btn_no:setName("btn_no")
btn_no:setTag(1634)
btn_no:setCascadeColorEnabled(true)
btn_no:setCascadeOpacityEnabled(true)
btn_no:setPosition(805.5595, 254.6320)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_no)
layout:setPositionPercentX(0.6293)
layout:setPositionPercentY(0.3537)
layout:setPercentWidth(0.1758)
layout:setPercentHeight(0.1000)
layout:setSize({width = 225.0000, height = 72.0000})
layout:setLeftMargin(693.0595)
layout:setRightMargin(361.9405)
layout:setTopMargin(429.3680)
layout:setBottomMargin(218.6320)
ruleBg:addChild(btn_no)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

