--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 300.0000, height = 105.0000})

--Create infoPanel
local infoPanel = ccui.Layout:create()
infoPanel:ignoreContentAdaptWithSize(false)
infoPanel:setClippingEnabled(false)
infoPanel:setBackGroundColorOpacity(102)
infoPanel:setTouchEnabled(true);
infoPanel:setLayoutComponentEnabled(true)
infoPanel:setName("infoPanel")
infoPanel:setTag(386)
infoPanel:setCascadeColorEnabled(true)
infoPanel:setCascadeOpacityEnabled(true)
infoPanel:setAnchorPoint(0.0000, 0.5000)
infoPanel:setPosition(38.2863, 75.1687)
layout = ccui.LayoutComponent:bindLayoutComponent(infoPanel)
layout:setPositionPercentX(0.1276)
layout:setPositionPercentY(0.7159)
layout:setPercentWidth(0.7000)
layout:setPercentHeight(0.4476)
layout:setSize({width = 210.0000, height = 47.0000})
layout:setLeftMargin(38.2863)
layout:setRightMargin(51.7137)
layout:setTopMargin(6.3313)
layout:setBottomMargin(51.6687)
Layer:addChild(infoPanel)

--Create coninL
local coninL = cc.Sprite:create("game/niuniu/resource/head/coninL.png")
coninL:setName("coninL")
coninL:setTag(663)
coninL:setCascadeColorEnabled(true)
coninL:setCascadeOpacityEnabled(true)
coninL:setPosition(105.2838, 21.9012)
layout = ccui.LayoutComponent:bindLayoutComponent(coninL)
layout:setPositionPercentX(0.5014)
layout:setPositionPercentY(0.4660)
layout:setPercentWidth(0.9190)
layout:setPercentHeight(0.9787)
layout:setSize({width = 193.0000, height = 46.0000})
layout:setLeftMargin(8.7838)
layout:setRightMargin(8.2162)
layout:setTopMargin(2.0988)
layout:setBottomMargin(-1.0988)
coninL:setBlendFunc({src = 1, dst = 771})
infoPanel:addChild(coninL)

--Create nickname_17
local nickname_17 = cc.Sprite:create("game/niuniu/resource/head/nickname.png")
nickname_17:setName("nickname_17")
nickname_17:setTag(178)
nickname_17:setCascadeColorEnabled(true)
nickname_17:setCascadeOpacityEnabled(true)
nickname_17:setPosition(80.4800, 22.9605)
layout = ccui.LayoutComponent:bindLayoutComponent(nickname_17)
layout:setPositionPercentX(0.3832)
layout:setPositionPercentY(0.4885)
layout:setPercentWidth(0.1381)
layout:setPercentHeight(0.6809)
layout:setSize({width = 29.0000, height = 32.0000})
layout:setLeftMargin(65.9800)
layout:setRightMargin(115.0200)
layout:setTopMargin(8.0395)
layout:setBottomMargin(6.9605)
nickname_17:setBlendFunc({src = 1, dst = 771})
infoPanel:addChild(nickname_17)

--Create m_pUserName
local m_pUserName = ccui.Text:create()
m_pUserName:ignoreContentAdaptWithSize(true)
m_pUserName:setTextAreaSize({width = 0, height = 0})
m_pUserName:setFontName("game/niuniu/resource/font/font.TTF")
m_pUserName:setFontSize(20)
m_pUserName:setString([[yourname]])
m_pUserName:setLayoutComponentEnabled(true)
m_pUserName:setName("m_pUserName")
m_pUserName:setTag(387)
m_pUserName:setCascadeColorEnabled(true)
m_pUserName:setCascadeOpacityEnabled(true)
m_pUserName:setAnchorPoint(0.0000, 0.5000)
m_pUserName:setPosition(100.4164, 20.4604)
layout = ccui.LayoutComponent:bindLayoutComponent(m_pUserName)
layout:setPositionPercentX(0.4782)
layout:setPositionPercentY(0.4353)
layout:setPercentWidth(0.4381)
layout:setPercentHeight(0.5106)
layout:setSize({width = 92.0000, height = 24.0000})
layout:setLeftMargin(100.4164)
layout:setRightMargin(17.5836)
layout:setTopMargin(14.5396)
layout:setBottomMargin(8.4604)
infoPanel:addChild(m_pUserName)

--Create coinPanel
local coinPanel = ccui.Layout:create()
coinPanel:ignoreContentAdaptWithSize(false)
coinPanel:setClippingEnabled(false)
coinPanel:setBackGroundColorOpacity(102)
coinPanel:setTouchEnabled(true);
coinPanel:setLayoutComponentEnabled(true)
coinPanel:setName("coinPanel")
coinPanel:setTag(398)
coinPanel:setCascadeColorEnabled(true)
coinPanel:setCascadeOpacityEnabled(true)
coinPanel:setPosition(39.1607, 1.4090)
layout = ccui.LayoutComponent:bindLayoutComponent(coinPanel)
layout:setPositionPercentX(0.1305)
layout:setPositionPercentY(0.0134)
layout:setPercentWidth(0.7000)
layout:setPercentHeight(0.4476)
layout:setSize({width = 210.0000, height = 47.0000})
layout:setLeftMargin(39.1607)
layout:setRightMargin(50.8393)
layout:setTopMargin(56.5910)
layout:setBottomMargin(1.4090)
Layer:addChild(coinPanel)

--Create coninL
local coninL = cc.Sprite:create("game/niuniu/resource/head/coninL.png")
coninL:setName("coninL")
coninL:setTag(664)
coninL:setCascadeColorEnabled(true)
coninL:setCascadeOpacityEnabled(true)
coninL:setPosition(104.1297, 23.0183)
layout = ccui.LayoutComponent:bindLayoutComponent(coninL)
layout:setPositionPercentX(0.4959)
layout:setPositionPercentY(0.4898)
layout:setPercentWidth(0.9190)
layout:setPercentHeight(0.9787)
layout:setSize({width = 193.0000, height = 46.0000})
layout:setLeftMargin(7.6297)
layout:setRightMargin(9.3703)
layout:setTopMargin(0.9817)
layout:setBottomMargin(0.0183)
coninL:setBlendFunc({src = 1, dst = 771})
coinPanel:addChild(coninL)

--Create coinIcon
local coinIcon = cc.Sprite:create("game/niuniu/resource/head/coinIcon.png")
coinIcon:setName("coinIcon")
coinIcon:setTag(662)
coinIcon:setCascadeColorEnabled(true)
coinIcon:setCascadeOpacityEnabled(true)
coinIcon:setPosition(79.6646, 22.9499)
layout = ccui.LayoutComponent:bindLayoutComponent(coinIcon)
layout:setPositionPercentX(0.3794)
layout:setPositionPercentY(0.4883)
layout:setPercentWidth(0.1571)
layout:setPercentHeight(0.7021)
layout:setSize({width = 33.0000, height = 33.0000})
layout:setLeftMargin(63.1646)
layout:setRightMargin(113.8354)
layout:setTopMargin(7.5501)
layout:setBottomMargin(6.4499)
coinIcon:setBlendFunc({src = 1, dst = 771})
coinPanel:addChild(coinIcon)

--Create m_pLableGameGold
local m_pLableGameGold = ccui.Text:create()
m_pLableGameGold:ignoreContentAdaptWithSize(true)
m_pLableGameGold:setTextAreaSize({width = 0, height = 0})
m_pLableGameGold:setFontName("game/niuniu/resource/font/font.TTF")
m_pLableGameGold:setFontSize(26)
m_pLableGameGold:setString([[0.00]])
m_pLableGameGold:setLayoutComponentEnabled(true)
m_pLableGameGold:setName("m_pLableGameGold")
m_pLableGameGold:setTag(399)
m_pLableGameGold:setCascadeColorEnabled(true)
m_pLableGameGold:setCascadeOpacityEnabled(true)
m_pLableGameGold:setAnchorPoint(0.0000, 0.5000)
m_pLableGameGold:setPosition(101.6364, 22.5538)
layout = ccui.LayoutComponent:bindLayoutComponent(m_pLableGameGold)
layout:setPositionPercentX(0.4840)
layout:setPositionPercentY(0.4799)
layout:setPercentWidth(0.2619)
layout:setPercentHeight(0.6596)
layout:setSize({width = 55.0000, height = 31.0000})
layout:setLeftMargin(101.6364)
layout:setRightMargin(53.3636)
layout:setTopMargin(8.9462)
layout:setBottomMargin(7.0538)
coinPanel:addChild(m_pLableGameGold)

--Create headPanel
local headPanel = ccui.Layout:create()
headPanel:ignoreContentAdaptWithSize(false)
headPanel:setClippingEnabled(false)
headPanel:setBackGroundColorOpacity(102)
headPanel:setTouchEnabled(true);
headPanel:setLayoutComponentEnabled(true)
headPanel:setName("headPanel")
headPanel:setTag(392)
headPanel:setCascadeColorEnabled(true)
headPanel:setCascadeOpacityEnabled(true)
headPanel:setAnchorPoint(0.5000, 0.5000)
headPanel:setPosition(47.5800, 53.1195)
layout = ccui.LayoutComponent:bindLayoutComponent(headPanel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1586)
layout:setPositionPercentY(0.5059)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.9905)
layout:setSize({width = 105.0000, height = 104.0000})
layout:setLeftMargin(-4.9200)
layout:setRightMargin(199.9200)
layout:setTopMargin(-0.1195)
layout:setBottomMargin(1.1195)
Layer:addChild(headPanel)

--Create game_head_bg
local game_head_bg = cc.Sprite:create("game/niuniu/resource/head/headbg.png")
game_head_bg:setName("game_head_bg")
game_head_bg:setTag(393)
game_head_bg:setCascadeColorEnabled(true)
game_head_bg:setCascadeOpacityEnabled(true)
game_head_bg:setPosition(51.4710, 51.1056)
layout = ccui.LayoutComponent:bindLayoutComponent(game_head_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4902)
layout:setPositionPercentY(0.4914)
layout:setPercentWidth(1.1619)
layout:setPercentHeight(1.1731)
layout:setSize({width = 122.0000, height = 122.0000})
layout:setLeftMargin(-9.5290)
layout:setRightMargin(-7.4710)
layout:setTopMargin(-8.1056)
layout:setBottomMargin(-9.8944)
game_head_bg:setBlendFunc({src = 1, dst = 771})
headPanel:addChild(game_head_bg)

--Create headImage
local headImage = ccui.ImageView:create()
headImage:ignoreContentAdaptWithSize(false)
headImage:loadTexture("game/niuniu/resource/head/headName1.png",0)
headImage:setLayoutComponentEnabled(true)
headImage:setName("headImage")
headImage:setTag(93)
headImage:setCascadeColorEnabled(true)
headImage:setCascadeOpacityEnabled(true)
headImage:setPosition(47.5268, 51.7954)
layout = ccui.LayoutComponent:bindLayoutComponent(headImage)
layout:setPositionPercentX(0.4526)
layout:setPositionPercentY(0.4980)
layout:setPercentWidth(0.9905)
layout:setPercentHeight(1.0000)
layout:setSize({width = 104.0000, height = 104.0000})
layout:setLeftMargin(-4.4732)
layout:setRightMargin(5.4732)
layout:setTopMargin(0.2046)
layout:setBottomMargin(-0.2046)
headPanel:addChild(headImage)

--Create game_prompt_banker
local game_prompt_banker = ccui.Text:create()
game_prompt_banker:ignoreContentAdaptWithSize(true)
game_prompt_banker:setTextAreaSize({width = 0, height = 0})
game_prompt_banker:setFontName("game/niuniu/resource/font/font.TTF")
game_prompt_banker:setFontSize(20)
game_prompt_banker:setString([[banker]])
game_prompt_banker:setLayoutComponentEnabled(true)
game_prompt_banker:setName("game_prompt_banker")
game_prompt_banker:setTag(1096)
game_prompt_banker:setCascadeColorEnabled(true)
game_prompt_banker:setCascadeOpacityEnabled(true)
game_prompt_banker:setVisible(false)
game_prompt_banker:setPosition(34.2492, 91.6142)
layout = ccui.LayoutComponent:bindLayoutComponent(game_prompt_banker)
layout:setPositionPercentX(0.3262)
layout:setPositionPercentY(0.8809)
layout:setPercentWidth(0.6190)
layout:setPercentHeight(0.2308)
layout:setSize({width = 65.0000, height = 24.0000})
layout:setLeftMargin(1.7492)
layout:setRightMargin(38.2508)
layout:setTopMargin(0.3858)
layout:setBottomMargin(79.6142)
headPanel:addChild(game_prompt_banker)

--Create win
local win = ccui.TextAtlas:create([[10000]],
													"Default/TextAtlas.png",
													18,
													27,
													"+")
win:setLayoutComponentEnabled(true)
win:setName("win")
win:setTag(427)
win:setCascadeColorEnabled(true)
win:setCascadeOpacityEnabled(true)
win:setVisible(false)
win:setPosition(47.3894, 55.1587)
layout = ccui.LayoutComponent:bindLayoutComponent(win)
layout:setPositionPercentX(0.4513)
layout:setPositionPercentY(0.5304)
layout:setPercentHeight(0.2596)
layout:setSize({width = 0.0000, height = 27.0000})
layout:setLeftMargin(47.3894)
layout:setRightMargin(57.6106)
layout:setTopMargin(35.3413)
layout:setBottomMargin(41.6587)
headPanel:addChild(win)

--Create lose
local lose = ccui.TextAtlas:create([[10000]],
													"Default/TextAtlas.png",
													18,
													27,
													"+")
lose:setLayoutComponentEnabled(true)
lose:setName("lose")
lose:setTag(428)
lose:setCascadeColorEnabled(true)
lose:setCascadeOpacityEnabled(true)
lose:setVisible(false)
lose:setPosition(47.1829, 56.1239)
layout = ccui.LayoutComponent:bindLayoutComponent(lose)
layout:setPositionPercentX(0.4494)
layout:setPositionPercentY(0.5397)
layout:setPercentHeight(0.2596)
layout:setSize({width = 0.0000, height = 27.0000})
layout:setLeftMargin(47.1829)
layout:setRightMargin(57.8171)
layout:setTopMargin(34.3761)
layout:setBottomMargin(42.6239)
headPanel:addChild(lose)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

